### ISSUE TITLE
SplitWindowというプラグインを同時に入れるとフリーズする

### ISSUE THREAD

**Issue by Greenjp0025** [oov/aviutl_gcmzdrops#32]
SplitWindow(4.6.0) 、ごちゃまぜドロップス(0.3.25) etc...
↑この環境で起動して、拡張編集にMP4をドロップするとエラー画面が表示され、
![AviUtl _ Application Exception 2023_10_24 21_18_21](https://github.com/oov/aviutl_gcmzdrops/assets/139126817/639ea3c3-56f6-4503-a631-9d516af6a7ef)
LOG 
[2023-10-25_01-47-55-956_12008.txt](https://github.com/oov/aviutl_gcmzdrops/files/13121817/2023-10-25_01-47-55-956_12008.txt)

 完全にAviutlが動かなくなります。（タスクマネージャーで強制終了しないとダメ）
 更新しても動かなくなります。
 SplitWindowまたはこのプラグイン、どちらかを抜けば動作するのですが、
 他の機能は異常ありません。

**Comment by Greenjp0025** [comment]
そしてちゃんと**exedit.auf と同じ場所**に入れてます

**Comment by oov** [comment]
その症状がごちゃまぜドロップス v0.4.0rc1 でも発生するか、試してみてください。

**Comment by Greenjp0025** [comment]
おはようございます。
分かりました、試してみます

**Comment by Greenjp0025** [comment]
出来ましたあああああああああああぁああああああああああああ！！！！！！！！！！1
