### ISSUE TITLE
おそらく"/"もしくは"\"が入っているmp4が読み込めない

### ISSUE THREAD

**Issue by UltraRaid** [oov/aviutl_gcmzdrops#33]
![スクリーンショット 2024-04-06 101837](https://github.com/oov/aviutl_gcmzdrops/assets/155785358/1816610f-45ce-4a74-9714-0abc0f21a341)
と出ます
"/"か"\"を抜くと読み込めます。

**Comment by oov** [comment]
それだと状況がわからないので、元の正確なファイル名を教えて下さい。

**Comment by oov** [comment]
返事が来ないのと、特に問題がない動作なので閉じます。

メッセージボックスが出たのは使用できない文字がファイル名に使用されていたからです。
問題になっている文字はメッセージボックス内で「?」で表示されています。
これはあなたが解決すべき問題であり、そもそも Issue を立てるべきではありません。

また、問題がある文字は恐らく `/` U+002F ではなく`⧸` U+29F8 です。
`/` はファイル名に含めることは絶対にできない文字なので、それを含むファイルは作成できません。

**Comment by UltraRaid** [comment]
返事遅くてほんとにすみません。

雑草 / ヒカキン＆セイキン.mp4です
