### ISSUE TITLE
処理モード「コピーを作成」の時にpngファイルのドロップに失敗する

### ISSUE THREAD

**Issue by totoki-kei** [oov/aviutl_gcmzdrops#7]
Ver0.2.2にて、ごちゃまぜドロップスの処理モードを「コピーを作成」に設定しpngファイルをドロップすると以下のダイアログが表示され失敗します。

```
---------------------------
ごちゃまぜドロップス
---------------------------
ドラッグ＆ドロップの処理中にエラーが発生しました。



problem occurred executing ondrop:

...pplications\aviutl\plugins\GCMZDrops\_entrypoint.lua:74: cannot open file
---------------------------
OK   
---------------------------

```

確認したところ、avoiddup.luaでデータ保存先フォルダにコピーされたファイルを、LuaDrop(L: Plua_State)(luafuncs.pas内)で処理しようとした際にエラーとなっているようです。
コピー済みファイルをCreateオープンしようとして失敗しているように見えます。

**Comment by oov** [comment]
報告ありがとうございました。
近日中に修正版をリリース予定です。

直接的な原因は「データ保存先」に配置されているファイルは直接読み込まなければならないところを、誤ってコピーしてから読み込もうとしたことによるものでした。
